name: agripartner_mobile
description: AgriPartnerAI Mobile Application for iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI
  cupertino_icons: ^1.0.6
  
  # State Management (lightweight and simple)
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Network
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Media
  camera: ^0.10.5+9
  permission_handler: ^11.1.0
  path_provider: ^2.1.2
  
  # Maps
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/