name: Deploy Backend to Cloud Run

on:
  push:
    branches: [main]
    paths: ['backend/**']
  workflow_dispatch:

env:
  PROJECT_ID: agripartnerai
  SERVICE_NAME: agripartner-backend-dev
  REGION: asia-southeast1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          cd backend
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
                       -t gcr.io/$PROJECT_ID/$SERVICE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --service-account pipeline-processor-dev@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars "GCP_PROJECT_ID=$PROJECT_ID" \
            --set-env-vars "GCP_REGION=$REGION" \
            --set-env-vars "ENVIRONMENT=dev" \
            --set-env-vars "GCS_INPUT_BUCKET=$PROJECT_ID-pipeline-input-dev" \
            --set-env-vars "GCS_OUTPUT_BUCKET=$PROJECT_ID-pipeline-output-dev" \
            --set-env-vars "GCS_TEMP_BUCKET=$PROJECT_ID-pipeline-temp-dev" \
            --memory 1Gi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 5

      - name: Output URL
        run: |
          echo "Deployed to: $(gcloud run services describe $SERVICE_NAME --region $REGION --format 'value(status.url)')"