name: Deploy Backend API

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '!backend/functions/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

env:
  PROJECT_ID: agripartnerai
  REGION: asia-northeast1
  SERVICE_NAME: agripartner-backend-dev
  REGISTRY: asia-northeast1-docker.pkg.dev
  REPOSITORY: agripartner-images

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Build and push Docker image
        run: |
          cd backend
          IMAGE_URI="${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.IMAGE_URI }} \
            --region=${{ env.REGION }} \
            --service-account=pipeline-processor-dev@${{ env.PROJECT_ID }}.iam.gserviceaccount.com \
            --memory=1Gi \
            --cpu=0.5 \
            --min-instances=0 \
            --max-instances=5 \
            --timeout=300 \
            --concurrency=80 \
            --cpu-throttling \
            --execution-environment=gen2 \
            --set-env-vars="GCP_PROJECT_ID=${{ env.PROJECT_ID }},GCP_REGION=${{ env.REGION }},ENVIRONMENT=dev,ENABLE_CLOUD_LOGGING=true,LOG_LEVEL=DEBUG,GCS_INPUT_BUCKET=agripartnerai-pipeline-input-dev,GCS_OUTPUT_BUCKET=agripartnerai-pipeline-output-dev,GCS_TEMP_BUCKET=agripartnerai-pipeline-temp-dev,VERTEX_AI_LOCATION=${{ env.REGION }},VERTEX_AI_MODEL=gemini-1.5-flash" \
            --allow-unauthenticated

      - name: Verify deployment
        run: |
          echo "Service URL:"
          gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --format="value(status.url)"