name: Deploy Frontend to Cloud Run

on:
  push:
    branches: [main]
    paths: ['frontend/**']
  workflow_dispatch:

env:
  PROJECT_ID: agripartnerai
  REGION: asia-northeast1
  SERVICE_NAME: agripartner-frontend-dev
  REGISTRY: asia-northeast1-docker.pkg.dev
  REPOSITORY: agripartner-images

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Get Backend URL
        id: backend-url
        run: |
          BACKEND_URL=$(gcloud run services describe agripartner-backend-dev --region ${{ env.REGION }} --format 'value(status.url)')
          echo "backend_url=$BACKEND_URL" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          cd frontend
          IMAGE_URI="${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          IMAGE_LATEST="${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:latest"
          docker build -t $IMAGE_URI -t $IMAGE_LATEST \
                       --build-arg NEXT_PUBLIC_API_URL=${{ steps.backend-url.outputs.backend_url }} \
                       --build-arg NEXT_PUBLIC_GCP_PROJECT_ID=${{ env.PROJECT_ID }} \
                       .
          docker push $IMAGE_URI
          docker push $IMAGE_LATEST
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.IMAGE_URI }} \
            --region=${{ env.REGION }} \
            --allow-unauthenticated \
            --memory=1Gi \
            --min-instances=0 \
            --max-instances=3 \
            --timeout=300 \
            --concurrency=80 \
            --execution-environment=gen2 \
            --set-env-vars="NEXT_PUBLIC_API_URL=${{ steps.backend-url.outputs.backend_url }},NEXT_PUBLIC_GCP_PROJECT_ID=${{ env.PROJECT_ID }},NEXT_PUBLIC_ENVIRONMENT=dev"

      - name: Verify deployment
        run: |
          echo "Service URL:"
          gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --format="value(status.url)"